---
- name: Ensure Pip is installed.
  package:
    name: "{{ pip_package }}"
    state: present
    update_cache: true

- name: Ensure pip_install_packages are installed (virtualenv).
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    extra_args: "{{ item.extra_args | default(omit) }}"
  loop: "{{ pip_install_packages_venv }}"

- name: Ensure pip_install_packages are installed (global).
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
    break_system_packages: true
    extra_args: "{{ item.extra_args | default(omit) }}"
  loop: "{{ pip_install_packages }}"
